Topic/metemctl token publish
nttcom/metemcyber pull request #65
Opened 2021-02-25 08:34 UTC by thinkersinker

MISPイベントをカタログに登録するコマンド metemctl publish を実装しました。
オプションに関しては-pで金額指定、-qでトークン量指定、-sで委託数指定が可能になっています。
よろしくお願いします。

2021-02-25 10:46 UTC, mshim03 reviewed
contract_metadata 取得の処理の関数化を検討してみてください (時間があれば)

2021-02-25 10:46 UTC, mshim03 commented on src/metemctl_publish.py
> +def deploy_CTItoken(w3, token_quantity, operators):
token_quantity に引数名を変更

2021-02-25 10:46 UTC, mshim03 commented on src/metemctl_publish.py
> +def create_metadata(misp_json_file, operators, token_price, token_quantity):
misp の jsonファイルから、metadataを作成

2021-02-25 10:46 UTC, mshim03 commented on src/metemctl_publish.py
> +    contract_metadata = json.loads(contract_json['metadata'])
contract_metadata 取得の処理は関数としてまとめてもいいかもしれないです

2021-02-26 02:05 UTC, nitky requested changes
w3の指定スタイルの統一（引数指定かグローバル）を確認お願いします :pray:

2021-02-26 02:05 UTC, nitky commented on src/metemctl_publish.py
> +        token_address = deploy_CTItoken(w3, token_quantity, operators)
デプロイする前にメタデータの存在確認をした方が良さそう

2021-02-26 02:05 UTC, nitky commented on src/metemctl_publish.py
> +        register_catalog(w3, catalog_address, token_address, cti_metadata)
カタログ登録する前にメタデータの存在確認をした方が良さそう

2021-02-26 02:05 UTC, nitky commented on src/metemctl_publish.py
> +        authorize_operator(token_address, broker_address)
ブローカーアドレスがちゃんと読み込めていることを確認

2021-02-26 02:05 UTC, nitky commented on src/metemctl_publish.py
> +def consign_token(w3, broker_address, catalog_address, token_address, stock):
w3を引数に指定

2021-02-26 02:05 UTC, nitky commented on src/metemctl_publish.py
> +        print('MISP EVENT: "' +
トランザクションが5回あるので、エラーチェックちゃんとした方が良さそう

2021-02-26 02:32 UTC, thinkersinker commented on src/metemctl_publish.py
> +def load_contract(contract_path, contract_key):
json内の対象データを取ってくるのに共通のkeyは存在しないため、contract_keyは逐一指定する必要があると判断しました。

2021-03-02 04:23 UTC, nitky approved these changes
LGTM!!!

2021-03-02 04:23 UTC, merged